name: Metrics
permissions:
  contents: write
on:
  schedule: [{ cron: '0 * * * *' }]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg

          base: header, activity, community, repositories, metadata

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_sections: most-used
          plugin_languages_limit: 8

          plugin_activity: yes
          plugin_activity_limit: 5

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes

          plugin_16personalities: yes
          plugin_16personalities_url: ${{ secrets.SIXTEEN_PERSONALITIES_URL }}
          plugin_16personalities_sections: personality, traits
          plugin_16personalities_scores: yes
